image: docker:latest

stages:
  - deploy

production-deploy:
  stage:  deploy
  image:  google/cloud-sdk
  tags:
    - linode
  environment:
    name: production
  services:
    - docker:dind
  script:
    - cat $ENVIRONMENT_DATA > .env
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=yaml/CloudBuild_Production.yaml
  only:
    - master

  


